project_id = "duedcqgrflmmmxmpdytu"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.purchase-voucher]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-booking-with-payment]
verify_jwt = false

[functions.confirm-payment-method]
verify_jwt = false

[functions.create-booking-setup-session]
verify_jwt = false
