// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duedcqgrflmmmxmpdytu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZWRjcWdyZmxtbW14bXBkeXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Njg2NzEsImV4cCI6MjA2ODA0NDY3MX0.o4u-NR2j3gYTkzjPDV3_Iu-Ru75W9KBwgetplEhuU_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});